### ISSUE TITLE
Flaky travis config

### ISSUE THREAD

**Issue by raipc** [axibase/atsd-web-test#27]
The Docker image used for the tests requires exact ATSD version. I use version-check endpoint to get latest ATSD version, but version-check info is updated before atsd packages are published which may lead to failed tests on ATSD installation stage.
Can we update version-check info as soon as packages are published?

**Comment by VeselovAlex** [comment]
Maybe something like this:
```sh
curl -s https://axibase.com/public/atsd_distrib_latest.htm | grep -oE 'atsd-distrib\\.(\\d+)' | head -n 1 | cut -f 2 -d .
```

**Comment by VeselovAlex** [comment]
Adapted to GNU grep
